name = "zavvetka-worker"
main = "src/index.ts"
compatibility_date = "2026-02-07"

workers_dev = true

[[kv_namespaces]]
binding = "NOTES_KV"
id = "361adcb4ec564344a01690b7d0cc66db"
preview_id = "1c20037efa4a4141a6da98cbd814f7e7"
